# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import items_pb2 as items__pb2


class ItemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetById = channel.unary_unary(
                '/items.ItemService/GetById',
                request_serializer=items__pb2.ItemRequest.SerializeToString,
                response_deserializer=items__pb2.Item.FromString,
                )
        self.PutItem = channel.unary_unary(
                '/items.ItemService/PutItem',
                request_serializer=items__pb2.Item.SerializeToString,
                response_deserializer=items__pb2.ItemResponse.FromString,
                )
        self.DeleteById = channel.unary_unary(
                '/items.ItemService/DeleteById',
                request_serializer=items__pb2.ItemRequest.SerializeToString,
                response_deserializer=items__pb2.Empty.FromString,
                )
        self.GetManyItems = channel.unary_stream(
                '/items.ItemService/GetManyItems',
                request_serializer=items__pb2.PaginationRequest.SerializeToString,
                response_deserializer=items__pb2.Item.FromString,
                )


class ItemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManyItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=items__pb2.ItemRequest.FromString,
                    response_serializer=items__pb2.Item.SerializeToString,
            ),
            'PutItem': grpc.unary_unary_rpc_method_handler(
                    servicer.PutItem,
                    request_deserializer=items__pb2.Item.FromString,
                    response_serializer=items__pb2.ItemResponse.SerializeToString,
            ),
            'DeleteById': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteById,
                    request_deserializer=items__pb2.ItemRequest.FromString,
                    response_serializer=items__pb2.Empty.SerializeToString,
            ),
            'GetManyItems': grpc.unary_stream_rpc_method_handler(
                    servicer.GetManyItems,
                    request_deserializer=items__pb2.PaginationRequest.FromString,
                    response_serializer=items__pb2.Item.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'items.ItemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ItemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/items.ItemService/GetById',
            items__pb2.ItemRequest.SerializeToString,
            items__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/items.ItemService/PutItem',
            items__pb2.Item.SerializeToString,
            items__pb2.ItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/items.ItemService/DeleteById',
            items__pb2.ItemRequest.SerializeToString,
            items__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetManyItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/items.ItemService/GetManyItems',
            items__pb2.PaginationRequest.SerializeToString,
            items__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
