# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: items.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bitems.proto\x12\x05items\"D\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\"\x19\n\x0bItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x0cItemResponse\x12\x19\n\x04item\x18\x01 \x01(\x0b\x32\x0b.items.Item\"=\n\x11PaginationRequest\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x13\n\x0bpage_length\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty2\xd7\x01\n\x0bItemService\x12,\n\x07GetById\x12\x12.items.ItemRequest\x1a\x0b.items.Item\"\x00\x12-\n\x07PutItem\x12\x0b.items.Item\x1a\x13.items.ItemResponse\"\x00\x12\x30\n\nDeleteById\x12\x12.items.ItemRequest\x1a\x0c.items.Empty\"\x00\x12\x39\n\x0cGetManyItems\x12\x18.items.PaginationRequest\x1a\x0b.items.Item\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'items_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEM._serialized_start=22
  _ITEM._serialized_end=90
  _ITEMREQUEST._serialized_start=92
  _ITEMREQUEST._serialized_end=117
  _ITEMRESPONSE._serialized_start=119
  _ITEMRESPONSE._serialized_end=160
  _PAGINATIONREQUEST._serialized_start=162
  _PAGINATIONREQUEST._serialized_end=223
  _EMPTY._serialized_start=225
  _EMPTY._serialized_end=232
  _ITEMSERVICE._serialized_start=235
  _ITEMSERVICE._serialized_end=450
# @@protoc_insertion_point(module_scope)
